---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-authenticator-{{ CONJUR_NAMESPACE_NAME }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "serviceaccounts", "replicationcontrollers", "deploymentconfigs"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"] # OpenShift 3.7+
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps.openshift.io"] # OpenShift 4.3+
  resources: [ "deploymentconfigs"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
