----
apiVersion: v1
kind: Service
metadata:
  name: conjur-master-ext
  labels:
    app: conjur-cluster-svc-ext
spec:
  # LoadBalancer is enabling our external-to-cluster ingress into
  # the master. This allows it to be usable from the outside of K8s.
  type: LoadBalancer
  selector:
    app: conjur-node
  ports:
  - name: https
    protocol: TCP
    port: 443
  - name: ldaps
    protocol: TCP
    port: 663
  - name: pg-main
    protocol: TCP
    port: 5432
  - name: syslog-audit
    protocol: TCP
    port: 1999
