apiVersion: v1
kind: Service
metadata:
  name: conjur-cluster-service
  labels:
    app: conjur-cluster-service
spec:
  clusterIP: None
  ports:
  - port: 443
    name: https
  selector:
    app: conjur-node
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: conjur-cluster
  name: conjur-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: conjur-node
  serviceName: conjur-cluster-service
  podManagementPolicy: Parallel  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-management-policies
  template:
    metadata:
      labels:
        app: conjur-node
        name: conjur-node
        role: unset # set to master or standby when configured
    spec:
      serviceAccountName: conjur-cluster
      containers:
      - name: conjur-appliance
        image: {{ CONJUR_APPLIANCE_IMAGE }}
        imagePullPolicy: {{ IMAGE_PULL_POLICY }}
        env:
          # Only required for Conjur v5
          - name: CONJUR_DATA_KEY
            value: "{{ CONJUR_DATA_KEY }}"
        command: ["/bin/sh"]
        args: ["-c", "bash -c 'if [ ! -d /opt/conjur/dbdata/9.4 ]; then mv /var/lib/postgresql/9.4 /opt/conjur/dbdata; mv /opt/conjur/etc /opt/conjur/data;mv /etc/runit/runsvdir /opt/conjur/data; mv /etc/ssl /opt/conjur/ssl;mv /etc/service /opt/conjur/data/runsvdir/default; fi; rm -rf /etc/service ;rm -rf /etc/runit/runsvdir; ln -sf /opt/conjur/data/runsvdir /etc/runit/runsvdir;ln -sf /opt/conjur/data/runsvdir/default /etc/service; chown -h conjur:root /opt/conjur/data; chmod 777 /opt/conjur/data;ln -sf /opt/conjur/data/etc /opt/conjur/etc;chown -h conjur:root /opt/conjur/etc ;chown -h conjur:root /opt/conjur/data/etc;chmod 777 /opt/conjur/data/etc; ln -sf /opt/conjur/ssl/ssl /etc/ssl; chmod 777 /opt/conjur/ssl; ln -sf /opt/conjur/dbdata/9.4 /var/lib/postgresql/9.4; chown -h postgres:postgres /var/lib/postgresql/9.4; chown -h postgres:postgres /opt/conjur/dbdata; chown -h conjur:root /opt/conjur/data; chmod 777 /opt/conjur/dbdata; chmod 777 /opt/conjur/ssl;' & /bin/keyctl session - /sbin/my_init" ]
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
        volumeMounts:
        - name: conjur-dbdata
          mountPath: /opt/conjur/dbdata
        - name: conjur-data
          mountPath: /opt/conjur/data
        - name: conjur-ssl
          mountPath: /opt/conjur/ssl
      imagePullSecrets:
        - name: dockerpullsecret
  volumeClaimTemplates:
  - metadata:
      name: conjur-dbdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: conjur-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: conjur-ssl
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi

